worlds:
  - { name: "world", requirement: "none", x: 70, y: 70, z: 70}
  - { name: "world_two", requirement: "combat>5", x: 70, y: 70, z: 70}
  - { name: "world_three", requirement: "combat>12", x: 70, y: 70, z: 70}